### PR TITLE
I added some shortcut function

### PR DESCRIPTION
**Pull request by solotimes**
Hello! I'm using MPlayerX for some time and I think it's the best video player on os x.
I added some shortcut keys:  using pageup/pagedown key to jump to previous/next movie file.
Really need this function , please add this to the master branch ,thank you!

### CODE REVIEW

**Comment by niltsh** [comment]
This is wonderful!!!
Thank you very much,

And may I have some suggestion?
1. As far as I know, in some of the macs, pageup/pagedown is really not visible in the keyboard, so how about to change it to  <, > ?
2. if Fuzzy search is on, or if the current being played file is named by xxx02yyy01, how does it find the previous one named by xxx01yyyNN, NN is the last file of the last season?

but after all, this is really a wonderful commit, I will check in to master in a few days, I will resolve the problem, or if you could help me to solve the issue I mentioned above, that will be a perfect commit.

and I will add some buttons...

**Comment by solotimes** [comment]
I'm glad you like it. 
You are right, the pageup/pagedown key is a problem on imac or some wireless keyboards(on mac book pro i can use fn+up/down). So i think we can just change this to <,> or provide a tab of the prereference pane to let the user custom the key binding themself.
And about the search algorithm , I think there might be a simple method: 
- first determine the prefix of the movie file,like 'xxx' of 'xxx02yyy01' <br />
- add all files with this prefix to a list <br />
- remove all non-digital characters of the file name and order the list by the digital strings left <br />
- use this list as the order of the files <br />
  I think this method can solve the problem. although the order is not very precise ,but in most situations it will get a correct order.
  I shall push another commit in a few days.
  Sorry for my bad english.

**Comment by niltsh** [comment]
You could totally make me understood, so the language is not a problem between us.

I will use <, >, for the shortcut, and I will add button in the controlbar, and also menu items.

About the algo, I will spend more time to figure it out, since a REAL Playlist function is on the way.

**Comment by niltsh** [comment]
This request, I will keep it until I finished the playlist function...

**Comment by niltsh** [comment]
kinds of rework, but next/prev now functions.

**Comment by niltsh** [comment]
the code is totally made on a scratch, so if you would like, you may take a interesting test.
Since Previous should be more powerful than what you have requested to me.

But yours is really a big hint for me to implement this.

Thank you for your attendance.

**Pull request closed without merging**
